dataset:
  random: true
  random_num_features: 100
  random_num_samples: 1000
  random_num_target: 1
  filepath: ""



model:
  method: "xgboost"
  nn:
   epoch: 3
   lr: 0.003
   input_dim: 100
   output_dim: 1
   batch_size: 2
  multivariate_regression:
   input_dim: 943
   output_dim: 1000
  kmeans:
   k: 7
   objective: 'euclidean'
  xgboost:
   objective: "reg:squarederror"
   n_estimators: 100
   lr: 0.1
   max_depth: 4




 