dataset:
  filepath1: ""
  filepath2: ""
  filepath3: ""


model:
  nn:
   lr: 0.003
   input_dim: 943
   output_dim: 1000
  multivariate:
   input_dim: 943
   output_dim: 1000
  kmeans:
   k: 7
   objective: 'euclidean'
  xgboost:
   param1: ''
   param2 : ''
   param3: ''

 